# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('fathername', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(default=0, verbose_name='День рождения')),
                ('student_ticket', models.CharField(max_length=50, verbose_name='Студенческий билет')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group', verbose_name='Группа студента')),
            ],
            options={
                'db_table': 'students',
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
