# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fathername',
            new_name='father_name',
        ),
    ]
