# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180224_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_ticket',
            new_name='student_card',
        ),
    ]
