# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Создано'), ('2', 'Модифицировано'), ('3', 'Удалено')], default='1', max_length=20, verbose_name='Используемое топливо')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('model', models.CharField(max_length=250, verbose_name='Class')),
                ('log', models.CharField(max_length=250, verbose_name='Log')),
            ],
            options={
                'verbose_name_plural': 'Loggers',
                'db_table': 'logger',
                'verbose_name': 'Logger',
            },
        ),
    ]
